-- COUNTRY
CREATE TABLE COUNTRY (
  ID INTEGER,
  NAME VARCHAR(128)
);

ALTER TABLE COUNTRY ADD CONSTRAINT COUNTRY_PK PRIMARY KEY(ID);

-- GENRE
CREATE TABLE GENRE (
  ID INTEGER,
  NAME VARCHAR(128)
);

ALTER TABLE GENRE ADD CONSTRAINT GENRE_PK PRIMARY KEY(ID);

-- DIRECTOR
CREATE TABLE DIRECTOR (
  ID INTEGER,
  COUNTRY_ID INTEGER,
  NAME VARCHAR(256)
);

ALTER TABLE DIRECTOR ADD CONSTRAINT DIRECTOR_PK PRIMARY KEY(ID);
ALTER TABLE DIRECTOR ADD CONSTRAINT DIRECTOR_COUNTRY_FK FOREIGN KEY(COUNTRY_ID) REFERENCES COUNTRY(ID);

-- FILM
CREATE TABLE FILM (
  ID INTEGER,
  NAME VARCHAR(256),
  NAME_ORIGINAL VARCHAR(256),
  -- YEAR
  DIRECTOR_ID INTEGER,
  COUNTRY_ID INTEGER
);

ALTER TABLE FILM ADD CONSTRAINT FILM_PK PRIMARY KEY(ID);
ALTER TABLE FILM ADD CONSTRAINT FILM_DIRECTOR_FK FOREIGN KEY(DIRECTOR_ID) REFERENCES DIRECTOR(ID);
ALTER TABLE FILM ADD CONSTRAINT FILM_COUNTRY_FK FOREIGN KEY(COUNTRY_ID) REFERENCES COUNTRY(ID);
