-- COUNTRY
INSERT INTO COUNTRY (ID, NAME) VALUES (1, 'Россия');
INSERT INTO COUNTRY (ID, NAME) VALUES (2, 'США');
INSERT INTO COUNTRY (ID, NAME) VALUES (3, 'Германия');
INSERT INTO COUNTRY (ID, NAME) VALUES (4, 'Италия');
INSERT INTO COUNTRY (ID, NAME) VALUES (5, 'Франция');
INSERT INTO COUNTRY (ID, NAME) VALUES (6, 'Мексика');

-- GENRE
INSERT INTO GENRE (ID, NAME) VALUES (1, 'Боевик');
INSERT INTO GENRE (ID, NAME) VALUES (2, 'Комедия');
INSERT INTO GENRE (ID, NAME) VALUES (3, 'Мелодрама');
INSERT INTO GENRE (ID, NAME) VALUES (4, 'Триллер');
INSERT INTO GENRE (ID, NAME) VALUES (5, 'Ужасы');
INSERT INTO GENRE (ID, NAME) VALUES (6, 'Эротика');
